services:
  database:
    image: mysql
    env_file: database/.env
    volumes:
      - .data:/var/lib/mysql
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  notes-api:
    build: api
    env_file: database/.env
    volumes:
      - ./notes:/app/notes
    ports:
      - 8001:8000
    command: ["run", "notes-api"]
    depends_on:
      - database
  education-api:
    build: api
    env_file: database/.env
    volumes:
      - ./notes:/app/notes
    ports:
      - 8002:8000
    command: ["run", "education-api"]
    depends_on:
      - database
    ports:
      - 3306:3306
  frontend:
    build: frontend
    env_file: frontend/.env
    depends_on:
      - education-api
    ports:
      - 8000:4321
